Make generation of protocol docs dependent on xml2rfc
If xml2rfc doesn't exist, skip generating the protocol documentation
in autogen and print out a warning.

Change-Id: I714872fb0e573c50f0d6912275324f483468499e
Reviewed-on: https://gerrit.stanford.edu/1305
Reviewed-by: Russ Allbery <rra@stanford.edu>
Tested-by: Russ Allbery <rra@stanford.edu>

diff --git a/autogen b/autogen
--- a/autogen
+++ b/autogen
@@ -35,7 +35,11 @@ lib/encoding-rules include/webauth/tokens.h                     \
     webauth_token_webkdc_proxy webauth_token_webkdc_service     \
     > lib/rules-tokens.c
 
-# Generate protocol documentation.
-cd docs
-xml2rfc protocol.xml protocol.html
-xml2rfc protocol.xml protocol.txt
+# Generate protocol documentation if xml2rfc is available.
+if command -v xml2rfc 2>&1 >/dev/null ; then
+    cd docs
+    xml2rfc protocol.xml protocol.html
+    xml2rfc protocol.xml protocol.txt
+else
+    echo 'xml2rfc not found, not building protocol documentation' >&2
+fi
