Pass the IP address into the webkdc-validate middleware call
The IP is needed to track on-campus versus off-campus logins for
the purposes of ensuring that the user's multifactor was set up by
themselves.  Adjust the library and test suite code accordingly.

Also remove some old debugging code left behind from previous
changes.

Change-Id: Ib3340298845621d421d5169b5099307eafbd15ef
Reviewed-on: https://gerrit.stanford.edu/131
Tested-by: Russ Allbery <rra@stanford.edu>
Reviewed-by: Russ Allbery <rra@stanford.edu>

diff --git a/tests/data/cmd-webkdc b/tests/data/cmd-webkdc
--- a/tests/data/cmd-webkdc
+++ b/tests/data/cmd-webkdc
@@ -19,6 +19,10 @@ if [ "$1" = "webkdc-userinfo" ] ; then
     fi
 elif [ "$1" = "webkdc-validate" ] ; then
     dir=validate
+    if [ "$3" != "127.0.0.1" ] ; then
+        echo "invalid IP address $3" >&2
+        exit 1
+    fi
 else
     echo "invalid command $1" >&2
     exit 1
@@ -29,7 +33,7 @@ if [ -f "data/xml/$dir/$2.xml" ] ; then
     if [ "$1" = "webkdc-userinfo" ] ; then
         exec cat "data/xml/$dir/$2.xml"
     elif [ "$1" = "webkdc-validate" ] ; then
-        if [ "$3" != "123456" ] ; then
+        if [ "$4" != "123456" ] ; then
             cat "data/xml/$dir/$2.xml" | sed 's/<success>yes/<success>no/'
             exit $?
         else
