Add libwebauth interface for validating a multifactor authentication
Add the webauth_user_validate function to validate an authentication
code, generally for OTP.  Currently, only the remctl metadata protocol
is supported.

Change-Id: Ie79ae4c3bad7eb33f4021df8c730d67b52987d58
Reviewed-on: https://gerrit.stanford.edu/121
Tested-by: Russ Allbery <rra@stanford.edu>
Reviewed-by: Russ Allbery <rra@stanford.edu>

diff --git a/tests/data/cmd-webkdc b/tests/data/cmd-webkdc
--- a/tests/data/cmd-webkdc
+++ b/tests/data/cmd-webkdc
@@ -17,6 +17,12 @@ if [ "$1" = "webkdc-userinfo" ] ; then
         echo "invalid random flag $5" >&2
         exit 1
     fi
+elif [ "$1" = "webkdc-validate" ] ; then
+    dir=validate
+    if [ "$3" != "127.0.0.1" ] ; then
+        echo "invalid IP address $3" >&2
+        exit 1
+    fi
 else
     echo "invalid command $1" >&2
     exit 1
@@ -24,7 +30,16 @@ fi
 
 # See if the file exists, and if so, return it.
 if [ -f "data/xml/$dir/$2.xml" ] ; then
-    exec cat "data/xml/$dir/$2.xml"
+    if [ "$1" = "webkdc-userinfo" ] ; then
+        exec cat "data/xml/$dir/$2.xml"
+    elif [ "$1" = "webkdc-validate" ] ; then
+        if [ "$5" != "123456" ] ; then
+            cat "data/xml/$dir/$2.xml" | sed 's/<success>yes/<success>no/'
+            exit $?
+        else
+            exec cat "data/xml/$dir/$2.xml"
+        fi
+    fi
 else
     echo "unknown user $2" >&2
     exit 1
