Add return URL to user information query, support errors
Pass the return URL to the user information service when making
queries.  Support returning an <error> element in the <authdata>
result and passing it back as part of the user information result.
Add a test for using this to implement URL restrictions.

Change-Id: Ia04ae4ed8e972cf7509f17b814baecedeb54595e
Reviewed-on: https://gerrit.stanford.edu/419
Reviewed-by: Russ Allbery <rra@stanford.edu>
Tested-by: Russ Allbery <rra@stanford.edu>

diff --git a/tests/data/cmd-webkdc b/tests/data/cmd-webkdc
--- a/tests/data/cmd-webkdc
+++ b/tests/data/cmd-webkdc
@@ -27,6 +27,10 @@ if [ "$1" = "webkdc-userinfo" ] ; then
         echo "invalid random flag $5" >&2
         exit 1
     fi
+    if [ -z "$6" ] ; then
+        echo 'missing return URL' >&2
+        exit 1
+    fi
 elif [ "$1" = "webkdc-validate" ] ; then
     dir=validate
     if [ "$3" != "127.0.0.1" ] ; then
@@ -53,6 +57,8 @@ if [ -f "data/xml/$dir/$2.xml" ] ; then
             cat "data/xml/$dir/$2.xml" \
                 | sed 's%<max%<multifactor-required /><max%'
             exit $?
+        elif [ "$6" = "https://example.com/restrict/" ] ; then
+            exec cat "data/xml/$dir/restrict.xml"
         else
             exec cat "data/xml/$dir/$2.xml"
         fi
